apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-depl
spec: 
  replicas: 1
  selector : 
    matchLabels:
      app : auth
  template : 
    metadata:
      labels:
        app : auth
    spec:
      containers:
        - name : auth
          image : technophilefirdous/auth
---
apiVersion : v1
kind: service
matadeta:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: tcp
      port: 3000
      targetport: 3000
